run:
  timeout: 3m
  skip-files: []
  skip-dirs: []

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 100
  gocognit:
    min-complexity: 100
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 150
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  nestif:
    min-complexity: 8

linters:
  enable-all: true
  disable:
    - maintidx
    - goimports
    - interfacer # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - golint # deprecated
    - cyclop # duplicate of gocyclo
    - bodyclose # Too many false positives: https://github.com/timakin/bodyclose/issues/30
    - dupl
    - testpackage
    - tparallel
    - paralleltest
    - nlreturn
    - wsl
    - exhaustive
    - exhaustivestruct
    - goerr113
    - wrapcheck
    - ifshort
    - noctx
    - lll
    - gomnd
    - forbidigo

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: []
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - goconst
        - funlen
        - godot
